//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPXetNghiemYTe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoXNBN
    {
        public int ID { get; set; }
        public int HoSoBNID { get; set; }
        public int XNID { get; set; }
        public Nullable<double> KetQua { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> NgayXN { get; set; }
    
        public virtual HoSoBN HoSoBN { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual XetNghiem XetNghiem { get; set; }
    }
}
