//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPXetNghiemYTe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoSoBN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoSoBN()
        {
            this.HoSoXNBNs = new HashSet<HoSoXNBN>();
        }
    
        public int ID { get; set; }
        public int BNID { get; set; }
        public System.DateTime NgayTao { get; set; }
        public int TrangThaiThanhToan { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoXNBN> HoSoXNBNs { get; set; }
    }
}
