//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPXetNghiemYTe.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLPXetNghiemYTEntities : DbContext
    {
        public QLPXetNghiemYTEntities()
            : base("name=QLPXetNghiemYTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenhNhan> BenhNhans { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<HoSoBN> HoSoBNs { get; set; }
        public virtual DbSet<HoSoXNBN> HoSoXNBNs { get; set; }
        public virtual DbSet<LoaiXN> LoaiXNs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhongBan> PhongBans { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<XetNghiem> XetNghiems { get; set; }
    
        public virtual ObjectResult<GetBNinHD_Result> GetBNinHD(Nullable<int> xNID)
        {
            var xNIDParameter = xNID.HasValue ?
                new ObjectParameter("XNID", xNID) :
                new ObjectParameter("XNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBNinHD_Result>("GetBNinHD", xNIDParameter);
        }
    
        public virtual ObjectResult<GetDonGiaXNinHSBN_Result> GetDonGiaXNinHSBN(Nullable<int> iDHSBN)
        {
            var iDHSBNParameter = iDHSBN.HasValue ?
                new ObjectParameter("IDHSBN", iDHSBN) :
                new ObjectParameter("IDHSBN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDonGiaXNinHSBN_Result>("GetDonGiaXNinHSBN", iDHSBNParameter);
        }
    
        public virtual ObjectResult<GetKQXN_Result> GetKQXN(Nullable<int> hSBNID)
        {
            var hSBNIDParameter = hSBNID.HasValue ?
                new ObjectParameter("HSBNID", hSBNID) :
                new ObjectParameter("HSBNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetKQXN_Result>("GetKQXN", hSBNIDParameter);
        }
    
        public virtual ObjectResult<GetXNinHSXN_Result> GetXNinHSXN(Nullable<int> hSBNID)
        {
            var hSBNIDParameter = hSBNID.HasValue ?
                new ObjectParameter("HSBNID", hSBNID) :
                new ObjectParameter("HSBNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetXNinHSXN_Result>("GetXNinHSXN", hSBNIDParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int UpdateStatusHSBN(Nullable<int> hSBNID)
        {
            var hSBNIDParameter = hSBNID.HasValue ?
                new ObjectParameter("HSBNID", hSBNID) :
                new ObjectParameter("HSBNID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatusHSBN", hSBNIDParameter);
        }
    }
}
