//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPXetNghiemYTe.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class XetNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XetNghiem()
        {
            this.HoSoXNBNs = new HashSet<HoSoXNBN>();
        }
    
        public int ID { get; set; }
        public string TenXn { get; set; }
        public double TriSoBTNamMin { get; set; }
        public double TriSoBTNuMin { get; set; }
        public string DonVi { get; set; }
        public int DonGia { get; set; }
        public int LoaiXNID { get; set; }
        public double TriSoBTNamMax { get; set; }
        public double TriSoBTNuMax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoSoXNBN> HoSoXNBNs { get; set; }
        public virtual LoaiXN LoaiXN { get; set; }
    }
}
